name = "gbr_ui_router"
version = "1.0.0"
target = "javascript"

description = "ðŸ“¡ Gleam UI SPA router library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "gleam-br", repo = "gbr_ui_router" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gbr_js = "~> 1.0.3"
gleam_stdlib = "~> 0.65.0"
gleam_regexp = "~> 1.1.1"

[dev-dependencies]
gleeunit = "~> 1.9.0"

[javascript]
typescript_declarations = true
